name: chocolatine
on: [push, pull_request]
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-BDX-2-1-chocolatine-alex.aubry.git
  EXECUTABLES: truc
jobs:
  check_repo_clean:
    runs-on: ubuntu-latest
    steps:
      - run: find . -name '#*#' -o -name '*~' -o -name '*pain_au_chocolat*' -o -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov' -o -follow -name tmp -not -type f | while read -r line; do { echo "::error file=$line, title=Unwanted file detected:$line#L1::$line"; }; done; if [ ${line+x} ]; then exit 1; fi; unset line
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_repo_clean
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: make
        timeout-minutes: 2
        run: make
      - name: make_clean
        run: make clean
  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: make_tests
        timeout-minutes: 2
        run: make tests_run
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
